const components = {
  small_gun_turret_top: [
    'top_singlegunturret',
  ],
  small_gun_turret_bottom: [
    'bottom_singlegunturret',
  ],
  data: {
    top_front: {
      id: 'top_front',
      name: 'Top front',
      img: '/shipdesign/top_front.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    top_command: {
      id: 'top_command',
      name: 'top command',
      img: '/shipdesign/top_command.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    top_engine: {
      id: 'top_engine',
      name: 'top engine',
      img: '/shipdesign/top_engine.svg',
      componentClass: 'engine',
      hp: 70,
      armor: 5,
      acceleration: 10,
      range: 1,
    },
    top_genneric1: {
      id: 'top_genneric1',
      name: 'top genneric1',
      img: '/shipdesign/top_genneric1.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    top_singlegunturret: {
      id: 'top_singlegunturret',
      name: 'top singlegunturret',
      img: '/shipdesign/top_singlegunturret.svg',
      componentClass: 'gun_turret_top',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
      damage: 15,
    },
    top_turretmount: {
      id: 'top_turretmount',
      name: 'top turretmount',
      img: '/shipdesign/top_turretmount.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    bottom_front: {
      id: 'bottom_front',
      name: 'bottom front',
      img: '/shipdesign/bottom_front.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    bottom_genneric1: {
      id: 'bottom_genneric1',
      name: 'bottom genneric1',
      img: '/shipdesign/bottom_genneric1.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    bottom_singlegunturret: {
      id: 'bottom_singlegunturret',
      name: 'bottom singlegunturret',
      img: '/shipdesign/bottom_singlegunturret.svg',
      componentClass: 'gun_turret_bottom',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
      damage: 15,
    },
    bottom_turretmount: {
      id: 'bottom_turretmount',
      name: 'bottom turretmount',
      img: '/shipdesign/bottom_turretmount.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    bottom_cargo: {
      id: 'bottom_cargo',
      name: 'bottom cargo',
      img: '/shipdesign/bottom_cargo.svg',
      componentClass: 'hull',
      hp: 70,
      armor: 5,
      acceleration: -0.5,
      range: 1,
    },
    bottom_engine: {
      id: 'bottom_engine',
      name: 'bottom engine',
      img: '/shipdesign/bottom_engine.svg',
      componentClass: 'engine',
      hp: 70,
      armor: 5,
      acceleration: 10,
      range: 1,
    },
  },
  get all() {
    delete this.all;
    const all = Object.keys(components.data);
    this.all = all;
    return all;
  },
  small: [
    {
      id: 'top_front',
      name: 'Top front',
      img: '/shipdesign/top_front.svg',
      componentClass: 'hull',
    }, {
      id: 'top_command',
      name: 'top command',
      img: '/shipdesign/top_command.svg',
      componentClass: 'hull',
    }, {
      id: 'top_engine',
      name: 'top engine',
      img: '/shipdesign/top_engine.svg',
      componentClass: 'engine',
    }, {
      id: 'top_genneric1',
      name: 'top genneric1',
      img: '/shipdesign/top_genneric1.svg',
      componentClass: 'hull',
    }, {
      id: 'top_singlegunturret',
      name: 'top singlegunturret',
      img: '/shipdesign/top_singlegunturret.svg',
      componentClass: 'gun_turret_top',
    }, {
      id: 'top_turretmount',
      name: 'top turretmount',
      img: '/shipdesign/top_turretmount.svg',
      componentClass: 'hull',
    }, {
      id: 'bottom_front',
      name: 'bottom front',
      img: '/shipdesign/bottom_front.svg',
      componentClass: 'hull',
    }, {
      id: 'bottom_genneric1',
      name: 'bottom genneric1',
      img: '/shipdesign/bottom_genneric1.svg',
      componentClass: 'hull',
    }, {
      id: 'bottom_singlegunturret',
      name: 'bottom singlegunturret',
      img: '/shipdesign/bottom_singlegunturret.svg',
      componentClass: 'gun_turret_bottom',
    }, {
      id: 'bottom_turretmount',
      name: 'bottom turretmount',
      img: '/shipdesign/bottom_turretmount.svg',
      componentClass: 'hull',
    }, {
      id: 'bottom_cargo',
      name: 'bottom cargo',
      img: '/shipdesign/bottom_cargo.svg',
      componentClass: 'hull',
    }, {
      id: 'bottom_engine',
      name: 'bottom engine',
      img: '/shipdesign/bottom_engine.svg',
      componentClass: 'engine',
    },
  ],
};

export { components as default };
